### ISSUE TITLE
Can the author elaborate on the design of the network connection?

### ISSUE THREAD

**Issue by Alan-dowayStudio** [kroese/virtual-dsm#54]
Can the author elaborate on the design of the network connection? I'm trying to figure out the connection between the 20.20.20.x CIDR block of the container itself and docker0 (172.17.0.x) that docker establishes for bridge mode. Because currently only bridge mode can connect containers. I'm thinking about how to connect containers in host mode or custom:br0 mode.
thanks.

**Comment by Alan-dowayStudio** [comment]
The method of creating a macvlan network that matches the local subnet I tried before and did not succeed. On the one hand, the default subnet of custom network br0 under the docker of the unraid platform is 192.168.0.0/24, and the newly created subnet conflicts with its address. Change the range of the default br0 CIDR block to a smaller one, and other containers cannot be connected to the network. Can you provide a complete example of the RAID platform for creating a MACVLAN network for VDSM?

**Comment by Alan-dowayStudio** [comment]
The host and container baota can be connected to each other.
![inbaota](https://user-images.githubusercontent.com/68498529/232971256-74568bc6-bec5-47e5-8042-9910a0ac19e2.jpg)
![unraid](https://user-images.githubusercontent.com/68498529/232971279-8ed11ca8-de58-42c1-9c48-da16bc72c94b.jpg)

**Comment by Alan-dowayStudio** [comment]
![br0](https://user-images.githubusercontent.com/68498529/232975018-8e0e72db-d897-487f-8b17-944e55e0f326.jpg)

**Comment by Alan-dowayStudio** [comment]
Similarly, using the br0 network type, the baota container of 192.168.168.8 can be connected, and the virtual-DSM container of 192.168.168.18 cannot be connected.
![unraid](https://user-images.githubusercontent.com/68498529/233042386-118306fc-54d5-4d10-a205-e0879980fee9.jpg)

**Comment by Phizulation** [comment]
No offense, but given that I have about 20 containers running on the Unraid Macvlan network, it's probably not an Unraid bug. I don't want to sound ungrateful because I think this project is great, but basic troubleshooting leads me to believe it's not an unraid bug. I also have my network on br0. 

I'll try to disable Host access when I have a chance, and maybe try ipvlan as well.

**Comment by Alan-dowayStudio** [comment]
![ka](https://user-images.githubusercontent.com/68498529/233271053-698b18d3-563d-4b80-affd-022b221c6a1b.jpg)
The new version keeps getting stuck at this step.

**Comment by Alan-dowayStudio** [comment]
![starting](https://user-images.githubusercontent.com/68498529/233283739-dde9a183-9654-465b-bfc3-3d96bf36d494.jpg)
[log.txt](https://github.com/kroese/virtual-dsm/files/11281489/log.txt)

**Comment by Alan-dowayStudio** [comment]
![debug](https://user-images.githubusercontent.com/68498529/233283895-d6e1b0e4-72fd-4380-a964-ee0f4e5faaa7.jpg)

**Comment by Alan-dowayStudio** [comment]
![br0](https://user-images.githubusercontent.com/68498529/233284158-adc8a943-35b3-4e8d-8819-1170b1fc0e5b.jpg)
![debug](https://user-images.githubusercontent.com/68498529/233284170-89d2fe08-dbac-4b93-b1fa-7446bafe6a25.jpg)

**Comment by Phizulation** [comment]
I don't much about coding or the virtual dsm, but is it possible to pass the MacVlan IP to the virtual dsm? Instead of trying to find a way to route the macvlan ip to the virtual ip, can we have the vdsm set as DHCP and maybe pull the ip from the macvlan?

I dont' know how much sense that makes.

**Comment by WarMachine228** [comment]
![image](https://user-images.githubusercontent.com/48219479/234929995-1786e2ba-67fd-406e-a0d5-541e0cd4010f.png)
I'm getting this on the logs.  The problem is I do not know how to put in the `--device-cgroup-rule='c 243:* rwm'`  in unraid.
I put it variable but im sure it is wrong as it is not an environment varialble.  If I put it as device it show as error.
![image](https://user-images.githubusercontent.com/48219479/234931615-8da5e80a-ebda-4777-b921-6da024cc3202.png)
Can anyone advise how to correct this?  Thanks

**Comment by WarMachine228** [comment]
Thanks Kroese for the advise.  That work!!! Got an IP via DHCP .  Now the vDSM is on another IP on my network not bridged in unraid IP.  Can access the vdsm storage via smb on that ip.
![image](https://user-images.githubusercontent.com/48219479/234941406-42db21e0-b64c-4e31-a3ad-085570459298.png)

**Comment by Alan-dowayStudio** [comment]
@WarMachine228 Have you implemented the BR0 network connection to VDSM? Please describe the method in detail. Thank you.

**Comment by WarMachine228** [comment]
@kroese ah yes. Enable host access did the trick.  Now can mount shares from unraid. Thank you

**Comment by WarMachine228** [comment]
@Alan-dowayStudio  yes using bro network. Juat follow @kroese  instructions above. I screenshot the whole unraid docker confog page later when I get home.

**Comment by WarMachine228** [comment]
This is my docker config for vDSM.  Can set a static ip on the Synology Control Panel after to set to the the IP you want.
![image](https://user-images.githubusercontent.com/48219479/235175354-9601bc55-54ec-4392-ac22-36e78193b256.png)

**Comment by WarMachine228** [comment]
My Extra parameter is: `--stop-timeout 60 --cap-add NET_ADMIN --device-cgroup-rule='c 243:* rwm'`
But as Kroese said your device-cgroup-rule number may be different.  Check your logs for the correct number,  Check my screenshot from a previous post where it showed the cgroup rule number to input.

**Comment by Alan-dowayStudio** [comment]
OK, the problem of direct connection to VDSM in BR0 mode has been solved. But it still needs to occupy two IP addresses, I believe we will find the perfect solution. My specific steps are:
1. Set the network mode to br0, the IP address is empty (automatically obtained), the DHCP variable is Y for installation, and the console prompts: ERROR: Cannot create TAP interface. Please add the following docker settings to your container: --device-cgroup-rule='c 243:* rwm' --device=/dev/vhost-net；
2. Edit configuration: display the advanced view, modify the extra parameters to --cap-add NET_ADMIN --stop-timeout 60 --device-cgroup-rule='c 243:* rwm' --device='/dev/vhost-net';
3. Start the container, after completing the installation, set the fixed IP address in the network configuration of the DSM control panel.

**Comment by zilchulant** [comment]
Thanks @Alan-dowayStudio I did as you described. However, I am stucked a little bit before it:
"ERROR: Capability NET_ADMIN has not been set. Please add the following docker setting to your container: --cap-add NET_ADMIN"
 which is interesting, as I already have set "Extra Paramters" to "_--cap-add NET_ADMIN --stop-timeout 60 --device-cgroup-rule='c 243:* rwm' --device='/dev/vhost-net'_"
Did you started and installed DSM before on the bridge network?

**Comment by Alan-dowayStudio** [comment]
yes

发自我的iPhone

**Comment by zilchulant** [comment]
Unfortunately not.
Still the same issue:

> Starting Virtual DSM for Docker v3.81...
> INFO: Container IP is 192.168.20.244 with gateway 192.168.20.1
> 
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.20.244  netmask 255.255.255.0  broadcast 192.168.20.255
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         loop  txqueuelen 1000  (Local Loopback)
> 
> default via 192.168.20.1 dev eth0 
> 192.168.20.0/24 dev eth0 proto kernel scope link src 192.168.20.244 
> 
> ++ ip link add link eth0 dsm_vlan type macvlan mode bridge
> ++ rc=2
> ++ ((  rc != 0  ))
> ++ echo -n 'ERROR: Capability NET_ADMIN has not been set (2/1). Please add the '
> **ERROR: Capability NET_ADMIN has not been set (2/1). Please add the following docker setting to your container: --cap-add NET_ADMIN**
> ++ echo 'following docker setting to your container: --cap-add NET_ADMIN'
> ++ exit 15

Now I am using the docker-compose addon. So my Compose File looks like this:
```
version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
            ALLOCATE: "N"
            CPU_CORES: "2"
            RAM_SIZE: "512M"
            DHCP: "Y"
            DEBUG: "Y"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c 510:* rwm'
        cap_add:
            - NET_ADMIN                       
        ports:
            - 5000:5000
        volumes:
            - /mnt/cache/docker/vdsm:/storage
        restart: on-failure
        stop_grace_period: 1m
        networks:
            br0:             
                ipv4_address: 192.168.20.244

networks:
    br0:
        external: true
```

The br0 Network is created by unraid and is a *ipvlan* network (at least for me? Didn't change it).
docker network inspect br0
```
[    {
        "Name": "br0",
        "Id": "<<>>",
        "Created": "2023-05-05T15:42:20.275804473+02:00", <<last boot time
        "Scope": "local",
        "Driver": "ipvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.20.0/24",
                    "IPRange": "192.168.20.128/26",
                    "Gateway": "192.168.20.1",
                    "AuxiliaryAddresses": {
                        "server": "192.168.20.2"
                    }                }            ]        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""        },
        "ConfigOnly": false,
        "Containers": {}        },
        "Options": {
            "parent": "br0"        },
        "Labels": {}    }]
```

**Comment by zilchulant** [comment]
Thanks, I got it working. Changed br0 to macvlan in Unraid settings. According to the dsm logs I had some network issues, however with
```
        networks:
            - br0
```
It does work. I got the message with changing device_group_rules and now **it's running!** Thank you very much!
